name: Detection CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install sigma pytest yamllint
      - name: List Files
        run: |
          ls -R
      - name: Run validate.py
        run: |
          python validate.py rules/windows/win_logon_failure.yml
